# -*- coding: utf-8 -*-
"""02_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWsDaD3JTiJwD8PADSZWB4a4vGDewhT0
"""

import pandas as pd

print("=" * 70)
print("Retail Customer Analytics - Data Cleaning")
print("=" * 70)

# -------------------------
# Load Dataset
# -------------------------

file_path = "online_retail_II.xlsx"

# Attempt to read directly without pd.ExcelFile to bypass potential parsing issues
df1 = pd.read_excel(file_path, sheet_name=0, engine='openpyxl')
df2 = pd.read_excel(file_path, sheet_name=1, engine='openpyxl')

df = pd.concat([df1, df2], ignore_index=True)

print("\nOriginal Shape :", df.shape)

# -------------------------
# Remove Duplicate Rows
# -------------------------

duplicates = df.duplicated().sum()

df = df.drop_duplicates()

print("\nDuplicates Removed :", duplicates)

# -------------------------
# Remove Missing Customer IDs
# -------------------------

missing_customer = df["Customer ID"].isna().sum()

df = df.dropna(subset=["Customer ID"])

print("Missing Customer IDs Removed :", missing_customer)

# -------------------------
# Remove Missing Product Description
# -------------------------

missing_description = df["Description"].isna().sum()

df = df.dropna(subset=["Description"])

print("Missing Descriptions Removed :", missing_description)

# -------------------------
# Remove Negative Quantity
# -------------------------

negative_quantity = (df["Quantity"] <= 0).sum()

df = df[df["Quantity"] > 0]

print("Negative Quantity Removed :", negative_quantity)

# -------------------------
# Remove Negative Price
# -------------------------

negative_price = (df["Price"] <= 0).sum()

df = df[df["Price"] > 0]

print("Negative Price Removed :", negative_price)

# -------------------------
# Remove Cancelled Orders
# -------------------------

cancelled_orders = df["Invoice"].astype(str).str.startswith("C").sum()

df = df[~df["Invoice"].astype(str).str.startswith("C")]

print("Cancelled Orders Removed :", cancelled_orders)

# -------------------------
# Create Revenue Column
# -------------------------

df["Revenue"] = df["Quantity"] * df["Price"]

print("\nRevenue Column Created")

# -------------------------
# Convert Customer ID
# -------------------------

df["Customer ID"] = df["Customer ID"].astype(int)

# -------------------------
# Final Shape
# -------------------------

print("\nFinal Shape :", df.shape)

print("\nRemaining Missing Values")

print(df.isnull().sum())

# -------------------------
# Save Clean Dataset
# -------------------------

df.to_csv(
    "data/processed/retail_clean.csv",
    index=False
)

print("\nClean Dataset Saved Successfully")
